default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: api_development
  username: api
  password: api

test:
  <<: *default
  host: localhost
  database: api_test
  username: api
  password: api

production:
  <<: *default
  pool: 10
  url: <%= ENV.fetch("POSTGRES_URL", "") %>
  prepared_statements: false
  advisory_locks: false
  database_tasks: false